database:
  active: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        order_updates: true
        batch_versioned_data: true
        jdbc:
          batch_size: 20

server:
  error:
    include-message: always
    include-binding-errors: always
